# Generated by Django 4.2.7 on 2025-12-02 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Summary"),
                            ("weekly", "Weekly Summary"),
                            ("monthly", "Monthly Summary"),
                            ("custom", "Custom Period"),
                        ],
                        max_length=20,
                        verbose_name="Summary Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("summary_text", models.TextField(verbose_name="Summary Text")),
                (
                    "key_insights",
                    models.JSONField(default=list, verbose_name="Key Insights"),
                ),
                (
                    "what_users_like",
                    models.TextField(blank=True, verbose_name="What Users Like"),
                ),
                (
                    "what_users_dislike",
                    models.TextField(blank=True, verbose_name="What Users Dislike"),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="Recommendations"),
                ),
                (
                    "metrics_snapshot",
                    models.JSONField(default=dict, verbose_name="Metrics Snapshot"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_summaries",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentiment Summary",
                "verbose_name_plural": "Sentiment Summaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="Topic")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "mention_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mention Count"
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(default=0.0, verbose_name="Average Sentiment"),
                ),
                (
                    "sample_posts",
                    models.JSONField(default=list, verbose_name="Sample Post IDs"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_trends",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Trend",
                "verbose_name_plural": "Topic Trends",
                "ordering": ["-date", "-mention_count"],
                "unique_together": {("brand", "topic", "date")},
            },
        ),
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50, verbose_name="Platform")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_posts",
                    models.PositiveIntegerField(default=0, verbose_name="Total Posts"),
                ),
                (
                    "avg_sentiment",
                    models.FloatField(default=0.0, verbose_name="Average Sentiment"),
                ),
                (
                    "avg_engagement",
                    models.FloatField(default=0.0, verbose_name="Average Engagement"),
                ),
                (
                    "top_posts",
                    models.JSONField(default=list, verbose_name="Top Post IDs"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_analytics",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Analytics",
                "verbose_name_plural": "Platform Analytics",
                "ordering": ["-date"],
                "unique_together": {("brand", "platform", "date")},
            },
        ),
        migrations.CreateModel(
            name="HourlyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Date Time")),
                (
                    "total_posts",
                    models.PositiveIntegerField(default=0, verbose_name="Total Posts"),
                ),
                (
                    "positive_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Positive Posts"
                    ),
                ),
                (
                    "neutral_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Neutral Posts"
                    ),
                ),
                (
                    "negative_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Negative Posts"
                    ),
                ),
                (
                    "avg_sentiment_score",
                    models.FloatField(
                        default=0.0, verbose_name="Average Sentiment Score"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_analytics",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hourly Analytics",
                "verbose_name_plural": "Hourly Analytics",
                "ordering": ["-datetime"],
                "unique_together": {("brand", "datetime")},
            },
        ),
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_posts",
                    models.PositiveIntegerField(default=0, verbose_name="Total Posts"),
                ),
                (
                    "posts_by_platform",
                    models.JSONField(default=dict, verbose_name="Posts by Platform"),
                ),
                (
                    "positive_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Positive Posts"
                    ),
                ),
                (
                    "neutral_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Neutral Posts"
                    ),
                ),
                (
                    "negative_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Negative Posts"
                    ),
                ),
                (
                    "avg_sentiment_score",
                    models.FloatField(
                        default=0.0, verbose_name="Average Sentiment Score"
                    ),
                ),
                (
                    "positive_ratio",
                    models.FloatField(default=0.0, verbose_name="Positive Ratio"),
                ),
                (
                    "neutral_ratio",
                    models.FloatField(default=0.0, verbose_name="Neutral Ratio"),
                ),
                (
                    "negative_ratio",
                    models.FloatField(default=0.0, verbose_name="Negative Ratio"),
                ),
                (
                    "total_likes",
                    models.PositiveIntegerField(default=0, verbose_name="Total Likes"),
                ),
                (
                    "total_shares",
                    models.PositiveIntegerField(default=0, verbose_name="Total Shares"),
                ),
                (
                    "total_comments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Comments"
                    ),
                ),
                (
                    "total_views",
                    models.PositiveIntegerField(default=0, verbose_name="Total Views"),
                ),
                (
                    "avg_engagement",
                    models.FloatField(default=0.0, verbose_name="Average Engagement"),
                ),
                (
                    "top_topics",
                    models.JSONField(default=list, verbose_name="Top Topics"),
                ),
                (
                    "emotions_distribution",
                    models.JSONField(
                        default=dict, verbose_name="Emotions Distribution"
                    ),
                ),
                (
                    "top_authors",
                    models.JSONField(default=list, verbose_name="Top Authors"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_analytics",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Analytics",
                "verbose_name_plural": "Daily Analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["brand", "date"], name="analytics_d_brand_i_5caa04_idx"
                    )
                ],
                "unique_together": {("brand", "date")},
            },
        ),
    ]
