# Generated by Django 4.2.7 on 2026-04-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentsummary',
            name='platform_analysis',
            field=models.TextField(blank=True, verbose_name='Platform Analysis'),
        ),
    ]
