# Generated by Django 4.2.7 on 2026-04-21 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="Key"
                    ),
                ),
                (
                    "value",
                    models.TextField(blank=True, default="", verbose_name="Value"),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("smtp", "SMTP Email"),
                            ("sms", "SMS"),
                            ("stripe", "Stripe Payments"),
                            ("notifications", "Notifications"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(default=False, verbose_name="Sensitive"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("setting_change", "Setting Changed"),
                            ("user_action", "User Action"),
                            ("system", "System Event"),
                            ("notification_sent", "Notification Sent"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "target",
                    models.CharField(blank=True, max_length=200, verbose_name="Target"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
