# Generated by Django 4.2.7 on 2026-04-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.URLField(blank=True, verbose_name='Logo URL')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=50, verbose_name='Plan')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('max_brands', models.IntegerField(default=3, verbose_name='Max Brands')),
                ('max_users', models.IntegerField(default=5, verbose_name='Max Users')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
