# Generated by Django 4.2.7 on 2025-12-02 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Plan Name"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monthly Price"
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Yearly Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PKR", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "max_brands",
                    models.PositiveIntegerField(default=1, verbose_name="Max Brands"),
                ),
                (
                    "max_posts_per_month",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Max Posts/Month"
                    ),
                ),
                (
                    "max_exports_per_month",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Max Exports/Month"
                    ),
                ),
                (
                    "data_retention_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Data Retention (Days)"
                    ),
                ),
                ("features", models.JSONField(default=list, verbose_name="Features")),
                (
                    "has_api_access",
                    models.BooleanField(default=False, verbose_name="API Access"),
                ),
                (
                    "has_advanced_analytics",
                    models.BooleanField(
                        default=False, verbose_name="Advanced Analytics"
                    ),
                ),
                (
                    "has_competitor_analysis",
                    models.BooleanField(
                        default=False, verbose_name="Competitor Analysis"
                    ),
                ),
                (
                    "has_custom_alerts",
                    models.BooleanField(default=False, verbose_name="Custom Alerts"),
                ),
                (
                    "has_ai_insights",
                    models.BooleanField(default=False, verbose_name="AI Insights"),
                ),
                (
                    "has_priority_support",
                    models.BooleanField(default=False, verbose_name="Priority Support"),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Popular Badge"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["sort_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Billing Cycle",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "brands_used",
                    models.PositiveIntegerField(default=0, verbose_name="Brands Used"),
                ),
                (
                    "posts_this_month",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Posts This Month"
                    ),
                ),
                (
                    "exports_this_month",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exports This Month"
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Payment"
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Billing"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PKR", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Payment Method"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment History",
                "verbose_name_plural": "Payment Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
