# Generated by Django 4.2.7 on 2025-12-02 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Brand Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brand_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Industry"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="List of keywords to track",
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "hashtags",
                    models.JSONField(
                        default=list,
                        help_text="List of hashtags to track",
                        verbose_name="Hashtags",
                    ),
                ),
                (
                    "excluded_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords to exclude",
                        verbose_name="Excluded Keywords",
                    ),
                ),
                (
                    "platforms",
                    models.JSONField(
                        default=list,
                        help_text="List of platforms to monitor: twitter, reddit, etc.",
                        verbose_name="Platforms",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "fetch_frequency",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Fetch Frequency (minutes)"
                    ),
                ),
                (
                    "last_fetch",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Data Fetch"
                    ),
                ),
                (
                    "alert_enabled",
                    models.BooleanField(default=True, verbose_name="Alerts Enabled"),
                ),
                (
                    "alert_threshold",
                    models.FloatField(
                        default=0.3,
                        help_text="Alert when negative sentiment exceeds this percentage (0-1)",
                        verbose_name="Negative Sentiment Alert Threshold",
                    ),
                ),
                (
                    "alert_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Alert Email"
                    ),
                ),
                (
                    "total_posts",
                    models.PositiveIntegerField(default=0, verbose_name="Total Posts"),
                ),
                (
                    "avg_sentiment",
                    models.FloatField(default=0.0, verbose_name="Average Sentiment"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Competitor brand for comparison",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitors",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter/X"),
                            ("reddit", "Reddit"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("news", "News Article"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "platform_id",
                    models.CharField(max_length=200, verbose_name="Platform ID"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Post URL"
                    ),
                ),
                (
                    "author_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Author ID"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Author Name"
                    ),
                ),
                (
                    "author_username",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Author Username"
                    ),
                ),
                (
                    "author_followers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Author Followers"
                    ),
                ),
                (
                    "author_verified",
                    models.BooleanField(default=False, verbose_name="Author Verified"),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "content_cleaned",
                    models.TextField(blank=True, verbose_name="Cleaned Content"),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Language"
                    ),
                ),
                (
                    "has_media",
                    models.BooleanField(default=False, verbose_name="Has Media"),
                ),
                (
                    "media_urls",
                    models.JSONField(default=list, verbose_name="Media URLs"),
                ),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="Likes")),
                (
                    "shares",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Shares/Retweets"
                    ),
                ),
                (
                    "comments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Comments/Replies"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Views")),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Sentiment",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="-1 to 1",
                        null=True,
                        verbose_name="Sentiment Score",
                    ),
                ),
                (
                    "sentiment_confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Sentiment Confidence"
                    ),
                ),
                (
                    "emotions",
                    models.JSONField(blank=True, default=dict, verbose_name="Emotions"),
                ),
                (
                    "topics",
                    models.JSONField(blank=True, default=list, verbose_name="Topics"),
                ),
                (
                    "aspects",
                    models.JSONField(blank=True, default=dict, verbose_name="Aspects"),
                ),
                (
                    "entities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Named Entities"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Is Processed"),
                ),
                ("is_spam", models.BooleanField(default=False, verbose_name="Is Spam")),
                ("posted_at", models.DateTimeField(verbose_name="Posted At")),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fetched At"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processed At"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Post",
                "verbose_name_plural": "Social Posts",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_id",
                    models.CharField(max_length=200, verbose_name="Comment ID"),
                ),
                (
                    "author_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Author ID"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Author Name"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "content_cleaned",
                    models.TextField(blank=True, verbose_name="Cleaned Content"),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Sentiment"
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Sentiment Score"
                    ),
                ),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="Likes")),
                ("posted_at", models.DateTimeField(verbose_name="Posted At")),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fetched At"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to="brands.socialpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Comment",
                "verbose_name_plural": "Post Comments",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="FetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50, verbose_name="Platform")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "posts_fetched",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Posts Fetched"
                    ),
                ),
                (
                    "posts_new",
                    models.PositiveIntegerField(default=0, verbose_name="New Posts"),
                ),
                (
                    "posts_duplicate",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duplicate Posts"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetch_logs",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fetch Log",
                "verbose_name_plural": "Fetch Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="BrandAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("negative_spike", "Negative Sentiment Spike"),
                            ("volume_spike", "Volume Spike"),
                            ("trending", "Trending Topic"),
                            ("influencer", "Influencer Mention"),
                            ("crisis", "Potential Crisis"),
                        ],
                        max_length=50,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="Metrics"),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(default=False, verbose_name="Acknowledged"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged At"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Resolved"),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution Notes"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="brands.brand",
                    ),
                ),
                (
                    "related_posts",
                    models.ManyToManyField(
                        blank=True, related_name="alerts", to="brands.socialpost"
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Alert",
                "verbose_name_plural": "Brand Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["brand", "posted_at"], name="brands_soci_brand_i_ef45de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["brand", "sentiment"], name="brands_soci_brand_i_6f9d4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["brand", "platform"], name="brands_soci_brand_i_ba83a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["is_processed"], name="brands_soci_is_proc_f0a46f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialpost",
            unique_together={("brand", "platform", "platform_id")},
        ),
        migrations.AlterUniqueTogether(
            name="postcomment",
            unique_together={("post", "platform_id")},
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("user", "name")},
        ),
    ]
