# Generated by Django 4.2.7 on 2026-04-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="api_keys",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-brand API keys: youtube_api_key, reddit_client_id, etc.",
                verbose_name="API Keys",
            ),
        ),
    ]
