# Generated by Django 4.2.7 on 2026-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0002_add_brand_api_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="api_keys",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-brand API keys: youtube_api_key, twitter_bearer_token, reddit_client_id, reddit_client_secret, facebook_access_token, news_api_key",
                verbose_name="API Keys",
            ),
        ),
    ]
