# Generated by Django 4.2.7 on 2026-04-24 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0003_add_company_ref_to_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brands", "0003_add_api_keys"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="brand",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Business this brand belongs to — all business members can access",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="admin_dashboard.company",
                verbose_name="Business",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="user",
            field=models.ForeignKey(
                help_text="User who created this brand",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("company", "name")},
        ),
    ]
